/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoAccordion {
    }
    interface DemoAlerts {
    }
    interface DemoAvatars {
    }
    interface DemoBackToTop {
    }
    interface DemoBadges {
    }
    interface DemoBreadcrumbs {
    }
    interface DemoButtons {
    }
    interface DemoCalendars {
    }
    interface DemoCards {
    }
    interface DemoDividers {
    }
    interface DemoDrawers {
    }
    interface DemoFileUpload {
    }
    interface DemoGithubButtons {
    }
    interface DemoGradientText {
    }
    interface DemoGrid {
    }
    interface DemoHeadings {
    }
    interface DemoImages {
    }
    interface DemoInputs {
    }
    interface DemoMenus {
    }
    interface DemoModals {
    }
    interface DemoNavs {
    }
    interface DemoOverlays {
    }
    interface DemoPagination {
    }
    interface DemoProgressBars {
    }
    interface DemoRanges {
    }
    interface DemoSite {
    }
    interface DemoTables {
    }
    interface DemoTabs {
    }
    interface DemoTags {
    }
    interface DemoTimelines {
    }
    interface DemoToggles {
    }
    interface DemoTrees {
    }
    interface DemoTyography {
    }
    interface DemoTypography {
    }
}
declare global {
    interface HTMLDemoAccordionElement extends Components.DemoAccordion, HTMLStencilElement {
    }
    var HTMLDemoAccordionElement: {
        prototype: HTMLDemoAccordionElement;
        new (): HTMLDemoAccordionElement;
    };
    interface HTMLDemoAlertsElement extends Components.DemoAlerts, HTMLStencilElement {
    }
    var HTMLDemoAlertsElement: {
        prototype: HTMLDemoAlertsElement;
        new (): HTMLDemoAlertsElement;
    };
    interface HTMLDemoAvatarsElement extends Components.DemoAvatars, HTMLStencilElement {
    }
    var HTMLDemoAvatarsElement: {
        prototype: HTMLDemoAvatarsElement;
        new (): HTMLDemoAvatarsElement;
    };
    interface HTMLDemoBackToTopElement extends Components.DemoBackToTop, HTMLStencilElement {
    }
    var HTMLDemoBackToTopElement: {
        prototype: HTMLDemoBackToTopElement;
        new (): HTMLDemoBackToTopElement;
    };
    interface HTMLDemoBadgesElement extends Components.DemoBadges, HTMLStencilElement {
    }
    var HTMLDemoBadgesElement: {
        prototype: HTMLDemoBadgesElement;
        new (): HTMLDemoBadgesElement;
    };
    interface HTMLDemoBreadcrumbsElement extends Components.DemoBreadcrumbs, HTMLStencilElement {
    }
    var HTMLDemoBreadcrumbsElement: {
        prototype: HTMLDemoBreadcrumbsElement;
        new (): HTMLDemoBreadcrumbsElement;
    };
    interface HTMLDemoButtonsElement extends Components.DemoButtons, HTMLStencilElement {
    }
    var HTMLDemoButtonsElement: {
        prototype: HTMLDemoButtonsElement;
        new (): HTMLDemoButtonsElement;
    };
    interface HTMLDemoCalendarsElement extends Components.DemoCalendars, HTMLStencilElement {
    }
    var HTMLDemoCalendarsElement: {
        prototype: HTMLDemoCalendarsElement;
        new (): HTMLDemoCalendarsElement;
    };
    interface HTMLDemoCardsElement extends Components.DemoCards, HTMLStencilElement {
    }
    var HTMLDemoCardsElement: {
        prototype: HTMLDemoCardsElement;
        new (): HTMLDemoCardsElement;
    };
    interface HTMLDemoDividersElement extends Components.DemoDividers, HTMLStencilElement {
    }
    var HTMLDemoDividersElement: {
        prototype: HTMLDemoDividersElement;
        new (): HTMLDemoDividersElement;
    };
    interface HTMLDemoDrawersElement extends Components.DemoDrawers, HTMLStencilElement {
    }
    var HTMLDemoDrawersElement: {
        prototype: HTMLDemoDrawersElement;
        new (): HTMLDemoDrawersElement;
    };
    interface HTMLDemoFileUploadElement extends Components.DemoFileUpload, HTMLStencilElement {
    }
    var HTMLDemoFileUploadElement: {
        prototype: HTMLDemoFileUploadElement;
        new (): HTMLDemoFileUploadElement;
    };
    interface HTMLDemoGithubButtonsElement extends Components.DemoGithubButtons, HTMLStencilElement {
    }
    var HTMLDemoGithubButtonsElement: {
        prototype: HTMLDemoGithubButtonsElement;
        new (): HTMLDemoGithubButtonsElement;
    };
    interface HTMLDemoGradientTextElement extends Components.DemoGradientText, HTMLStencilElement {
    }
    var HTMLDemoGradientTextElement: {
        prototype: HTMLDemoGradientTextElement;
        new (): HTMLDemoGradientTextElement;
    };
    interface HTMLDemoGridElement extends Components.DemoGrid, HTMLStencilElement {
    }
    var HTMLDemoGridElement: {
        prototype: HTMLDemoGridElement;
        new (): HTMLDemoGridElement;
    };
    interface HTMLDemoHeadingsElement extends Components.DemoHeadings, HTMLStencilElement {
    }
    var HTMLDemoHeadingsElement: {
        prototype: HTMLDemoHeadingsElement;
        new (): HTMLDemoHeadingsElement;
    };
    interface HTMLDemoImagesElement extends Components.DemoImages, HTMLStencilElement {
    }
    var HTMLDemoImagesElement: {
        prototype: HTMLDemoImagesElement;
        new (): HTMLDemoImagesElement;
    };
    interface HTMLDemoInputsElement extends Components.DemoInputs, HTMLStencilElement {
    }
    var HTMLDemoInputsElement: {
        prototype: HTMLDemoInputsElement;
        new (): HTMLDemoInputsElement;
    };
    interface HTMLDemoMenusElement extends Components.DemoMenus, HTMLStencilElement {
    }
    var HTMLDemoMenusElement: {
        prototype: HTMLDemoMenusElement;
        new (): HTMLDemoMenusElement;
    };
    interface HTMLDemoModalsElement extends Components.DemoModals, HTMLStencilElement {
    }
    var HTMLDemoModalsElement: {
        prototype: HTMLDemoModalsElement;
        new (): HTMLDemoModalsElement;
    };
    interface HTMLDemoNavsElement extends Components.DemoNavs, HTMLStencilElement {
    }
    var HTMLDemoNavsElement: {
        prototype: HTMLDemoNavsElement;
        new (): HTMLDemoNavsElement;
    };
    interface HTMLDemoOverlaysElement extends Components.DemoOverlays, HTMLStencilElement {
    }
    var HTMLDemoOverlaysElement: {
        prototype: HTMLDemoOverlaysElement;
        new (): HTMLDemoOverlaysElement;
    };
    interface HTMLDemoPaginationElement extends Components.DemoPagination, HTMLStencilElement {
    }
    var HTMLDemoPaginationElement: {
        prototype: HTMLDemoPaginationElement;
        new (): HTMLDemoPaginationElement;
    };
    interface HTMLDemoProgressBarsElement extends Components.DemoProgressBars, HTMLStencilElement {
    }
    var HTMLDemoProgressBarsElement: {
        prototype: HTMLDemoProgressBarsElement;
        new (): HTMLDemoProgressBarsElement;
    };
    interface HTMLDemoRangesElement extends Components.DemoRanges, HTMLStencilElement {
    }
    var HTMLDemoRangesElement: {
        prototype: HTMLDemoRangesElement;
        new (): HTMLDemoRangesElement;
    };
    interface HTMLDemoSiteElement extends Components.DemoSite, HTMLStencilElement {
    }
    var HTMLDemoSiteElement: {
        prototype: HTMLDemoSiteElement;
        new (): HTMLDemoSiteElement;
    };
    interface HTMLDemoTablesElement extends Components.DemoTables, HTMLStencilElement {
    }
    var HTMLDemoTablesElement: {
        prototype: HTMLDemoTablesElement;
        new (): HTMLDemoTablesElement;
    };
    interface HTMLDemoTabsElement extends Components.DemoTabs, HTMLStencilElement {
    }
    var HTMLDemoTabsElement: {
        prototype: HTMLDemoTabsElement;
        new (): HTMLDemoTabsElement;
    };
    interface HTMLDemoTagsElement extends Components.DemoTags, HTMLStencilElement {
    }
    var HTMLDemoTagsElement: {
        prototype: HTMLDemoTagsElement;
        new (): HTMLDemoTagsElement;
    };
    interface HTMLDemoTimelinesElement extends Components.DemoTimelines, HTMLStencilElement {
    }
    var HTMLDemoTimelinesElement: {
        prototype: HTMLDemoTimelinesElement;
        new (): HTMLDemoTimelinesElement;
    };
    interface HTMLDemoTogglesElement extends Components.DemoToggles, HTMLStencilElement {
    }
    var HTMLDemoTogglesElement: {
        prototype: HTMLDemoTogglesElement;
        new (): HTMLDemoTogglesElement;
    };
    interface HTMLDemoTreesElement extends Components.DemoTrees, HTMLStencilElement {
    }
    var HTMLDemoTreesElement: {
        prototype: HTMLDemoTreesElement;
        new (): HTMLDemoTreesElement;
    };
    interface HTMLDemoTyographyElement extends Components.DemoTyography, HTMLStencilElement {
    }
    var HTMLDemoTyographyElement: {
        prototype: HTMLDemoTyographyElement;
        new (): HTMLDemoTyographyElement;
    };
    interface HTMLDemoTypographyElement extends Components.DemoTypography, HTMLStencilElement {
    }
    var HTMLDemoTypographyElement: {
        prototype: HTMLDemoTypographyElement;
        new (): HTMLDemoTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "demo-accordion": HTMLDemoAccordionElement;
        "demo-alerts": HTMLDemoAlertsElement;
        "demo-avatars": HTMLDemoAvatarsElement;
        "demo-back-to-top": HTMLDemoBackToTopElement;
        "demo-badges": HTMLDemoBadgesElement;
        "demo-breadcrumbs": HTMLDemoBreadcrumbsElement;
        "demo-buttons": HTMLDemoButtonsElement;
        "demo-calendars": HTMLDemoCalendarsElement;
        "demo-cards": HTMLDemoCardsElement;
        "demo-dividers": HTMLDemoDividersElement;
        "demo-drawers": HTMLDemoDrawersElement;
        "demo-file-upload": HTMLDemoFileUploadElement;
        "demo-github-buttons": HTMLDemoGithubButtonsElement;
        "demo-gradient-text": HTMLDemoGradientTextElement;
        "demo-grid": HTMLDemoGridElement;
        "demo-headings": HTMLDemoHeadingsElement;
        "demo-images": HTMLDemoImagesElement;
        "demo-inputs": HTMLDemoInputsElement;
        "demo-menus": HTMLDemoMenusElement;
        "demo-modals": HTMLDemoModalsElement;
        "demo-navs": HTMLDemoNavsElement;
        "demo-overlays": HTMLDemoOverlaysElement;
        "demo-pagination": HTMLDemoPaginationElement;
        "demo-progress-bars": HTMLDemoProgressBarsElement;
        "demo-ranges": HTMLDemoRangesElement;
        "demo-site": HTMLDemoSiteElement;
        "demo-tables": HTMLDemoTablesElement;
        "demo-tabs": HTMLDemoTabsElement;
        "demo-tags": HTMLDemoTagsElement;
        "demo-timelines": HTMLDemoTimelinesElement;
        "demo-toggles": HTMLDemoTogglesElement;
        "demo-trees": HTMLDemoTreesElement;
        "demo-tyography": HTMLDemoTyographyElement;
        "demo-typography": HTMLDemoTypographyElement;
    }
}
declare namespace LocalJSX {
    interface DemoAccordion {
    }
    interface DemoAlerts {
    }
    interface DemoAvatars {
    }
    interface DemoBackToTop {
    }
    interface DemoBadges {
    }
    interface DemoBreadcrumbs {
    }
    interface DemoButtons {
    }
    interface DemoCalendars {
    }
    interface DemoCards {
    }
    interface DemoDividers {
    }
    interface DemoDrawers {
    }
    interface DemoFileUpload {
    }
    interface DemoGithubButtons {
    }
    interface DemoGradientText {
    }
    interface DemoGrid {
    }
    interface DemoHeadings {
    }
    interface DemoImages {
    }
    interface DemoInputs {
    }
    interface DemoMenus {
    }
    interface DemoModals {
    }
    interface DemoNavs {
    }
    interface DemoOverlays {
    }
    interface DemoPagination {
    }
    interface DemoProgressBars {
    }
    interface DemoRanges {
    }
    interface DemoSite {
    }
    interface DemoTables {
    }
    interface DemoTabs {
    }
    interface DemoTags {
    }
    interface DemoTimelines {
    }
    interface DemoToggles {
    }
    interface DemoTrees {
    }
    interface DemoTyography {
    }
    interface DemoTypography {
    }
    interface IntrinsicElements {
        "demo-accordion": DemoAccordion;
        "demo-alerts": DemoAlerts;
        "demo-avatars": DemoAvatars;
        "demo-back-to-top": DemoBackToTop;
        "demo-badges": DemoBadges;
        "demo-breadcrumbs": DemoBreadcrumbs;
        "demo-buttons": DemoButtons;
        "demo-calendars": DemoCalendars;
        "demo-cards": DemoCards;
        "demo-dividers": DemoDividers;
        "demo-drawers": DemoDrawers;
        "demo-file-upload": DemoFileUpload;
        "demo-github-buttons": DemoGithubButtons;
        "demo-gradient-text": DemoGradientText;
        "demo-grid": DemoGrid;
        "demo-headings": DemoHeadings;
        "demo-images": DemoImages;
        "demo-inputs": DemoInputs;
        "demo-menus": DemoMenus;
        "demo-modals": DemoModals;
        "demo-navs": DemoNavs;
        "demo-overlays": DemoOverlays;
        "demo-pagination": DemoPagination;
        "demo-progress-bars": DemoProgressBars;
        "demo-ranges": DemoRanges;
        "demo-site": DemoSite;
        "demo-tables": DemoTables;
        "demo-tabs": DemoTabs;
        "demo-tags": DemoTags;
        "demo-timelines": DemoTimelines;
        "demo-toggles": DemoToggles;
        "demo-trees": DemoTrees;
        "demo-tyography": DemoTyography;
        "demo-typography": DemoTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-accordion": LocalJSX.DemoAccordion & JSXBase.HTMLAttributes<HTMLDemoAccordionElement>;
            "demo-alerts": LocalJSX.DemoAlerts & JSXBase.HTMLAttributes<HTMLDemoAlertsElement>;
            "demo-avatars": LocalJSX.DemoAvatars & JSXBase.HTMLAttributes<HTMLDemoAvatarsElement>;
            "demo-back-to-top": LocalJSX.DemoBackToTop & JSXBase.HTMLAttributes<HTMLDemoBackToTopElement>;
            "demo-badges": LocalJSX.DemoBadges & JSXBase.HTMLAttributes<HTMLDemoBadgesElement>;
            "demo-breadcrumbs": LocalJSX.DemoBreadcrumbs & JSXBase.HTMLAttributes<HTMLDemoBreadcrumbsElement>;
            "demo-buttons": LocalJSX.DemoButtons & JSXBase.HTMLAttributes<HTMLDemoButtonsElement>;
            "demo-calendars": LocalJSX.DemoCalendars & JSXBase.HTMLAttributes<HTMLDemoCalendarsElement>;
            "demo-cards": LocalJSX.DemoCards & JSXBase.HTMLAttributes<HTMLDemoCardsElement>;
            "demo-dividers": LocalJSX.DemoDividers & JSXBase.HTMLAttributes<HTMLDemoDividersElement>;
            "demo-drawers": LocalJSX.DemoDrawers & JSXBase.HTMLAttributes<HTMLDemoDrawersElement>;
            "demo-file-upload": LocalJSX.DemoFileUpload & JSXBase.HTMLAttributes<HTMLDemoFileUploadElement>;
            "demo-github-buttons": LocalJSX.DemoGithubButtons & JSXBase.HTMLAttributes<HTMLDemoGithubButtonsElement>;
            "demo-gradient-text": LocalJSX.DemoGradientText & JSXBase.HTMLAttributes<HTMLDemoGradientTextElement>;
            "demo-grid": LocalJSX.DemoGrid & JSXBase.HTMLAttributes<HTMLDemoGridElement>;
            "demo-headings": LocalJSX.DemoHeadings & JSXBase.HTMLAttributes<HTMLDemoHeadingsElement>;
            "demo-images": LocalJSX.DemoImages & JSXBase.HTMLAttributes<HTMLDemoImagesElement>;
            "demo-inputs": LocalJSX.DemoInputs & JSXBase.HTMLAttributes<HTMLDemoInputsElement>;
            "demo-menus": LocalJSX.DemoMenus & JSXBase.HTMLAttributes<HTMLDemoMenusElement>;
            "demo-modals": LocalJSX.DemoModals & JSXBase.HTMLAttributes<HTMLDemoModalsElement>;
            "demo-navs": LocalJSX.DemoNavs & JSXBase.HTMLAttributes<HTMLDemoNavsElement>;
            "demo-overlays": LocalJSX.DemoOverlays & JSXBase.HTMLAttributes<HTMLDemoOverlaysElement>;
            "demo-pagination": LocalJSX.DemoPagination & JSXBase.HTMLAttributes<HTMLDemoPaginationElement>;
            "demo-progress-bars": LocalJSX.DemoProgressBars & JSXBase.HTMLAttributes<HTMLDemoProgressBarsElement>;
            "demo-ranges": LocalJSX.DemoRanges & JSXBase.HTMLAttributes<HTMLDemoRangesElement>;
            "demo-site": LocalJSX.DemoSite & JSXBase.HTMLAttributes<HTMLDemoSiteElement>;
            "demo-tables": LocalJSX.DemoTables & JSXBase.HTMLAttributes<HTMLDemoTablesElement>;
            "demo-tabs": LocalJSX.DemoTabs & JSXBase.HTMLAttributes<HTMLDemoTabsElement>;
            "demo-tags": LocalJSX.DemoTags & JSXBase.HTMLAttributes<HTMLDemoTagsElement>;
            "demo-timelines": LocalJSX.DemoTimelines & JSXBase.HTMLAttributes<HTMLDemoTimelinesElement>;
            "demo-toggles": LocalJSX.DemoToggles & JSXBase.HTMLAttributes<HTMLDemoTogglesElement>;
            "demo-trees": LocalJSX.DemoTrees & JSXBase.HTMLAttributes<HTMLDemoTreesElement>;
            "demo-tyography": LocalJSX.DemoTyography & JSXBase.HTMLAttributes<HTMLDemoTyographyElement>;
            "demo-typography": LocalJSX.DemoTypography & JSXBase.HTMLAttributes<HTMLDemoTypographyElement>;
        }
    }
}
